version: "3"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13.4
    restart: always
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    